-- Altares ARA: composições exclusivas (pedras naturais na bandeja dourada).
-- Preço = soma das pedras no site + R$ 20 da bandeja; custo = custo das pedras + R$ 12 da bandeja.
-- As pedras avulsas que foram para os altares saem do site (são as mesmas peças físicas).

update public.ara_config set valor = '[{"id": "altar", "nome": "Altares ARA", "intro": "Composições exclusivas, montadas à mão sobre a bandeja dourada. Cada altar reúne pedras escolhidas para uma intenção e existe uma única vez."}]'::jsonb || valor where chave = 'categorias' and not (valor @> '[{"id":"altar"}]');

insert into public.ara_produtos (slug, nome, tag, frase, texto, preco, rotulo, variantes, detalhes, uso, cuidados, foto_url, fotos, disponivel, sem_adicional, ativo, ordem, seo_titulo, seo_descricao, estoque, categoria, destaque, custo)
values ('altar-da-prosperidade', 'Altar da Prosperidade · Pirita', 'Exclusivo · Peça única', 'Três piritas brutas sobre a bandeja dourada: um altar da prosperidade pronto para a mesa de trabalho.', 'Na tradição dos cristais, a pirita é a pedra da prosperidade, da abundância e da proteção do que é seu. Neste altar, três piritas brutas, escolhidas à mão pelo brilho, repousam sobre uma bandeja oval dourada que reflete a luz e multiplica o brilho das pedras.

Uma composição exclusiva da ARA, montada à mão: as pedras são naturais e esta combinação existe uma única vez.', 180, '', '[]'::jsonb, '[{"k": "Pedras", "v": "Três piritas brutas naturais"}, {"k": "Bandeja", "v": "Oval, de metal dourado"}, {"k": "Significado", "v": "Prosperidade, abundância e proteção do que é seu."}, {"k": "Exclusividade", "v": "Composição única, montada à mão pela ARA: não existe outra igual."}, {"k": "Foto", "v": "As fotos são do próprio altar que você vai receber."}]'::jsonb, 'Coloque na mesa de trabalho, perto do caixa ou na entrada da casa: na tradição, a pirita fica onde o dinheiro e os projetos começam.', 'A pirita não gosta de água nem de umidade: limpe só com pincel macio ou pano seco. A bandeja, com pano macio.', '/img/loja/altar-da-prosperidade.b75ddd14.jpg', '[]'::jsonb, true, true, true, 0, 'Altar da Prosperidade: pirita na bandeja dourada | ARA', 'Três piritas brutas naturais sobre bandeja oval dourada: um altar da prosperidade pronto para a mesa de trabalho. Peça única, montada à mão. Loja ARA.', 1, 'altar', true, 2 * coalesce((select custo from public.ara_produtos where slug = 'pirita-bruta'), 0) + 1 * coalesce((select custo from public.ara_produtos where slug = 'pirita-bruta-pequena'), 0) + 12)
on conflict (slug) do nothing;

insert into public.ara_produtos (slug, nome, tag, frase, texto, preco, rotulo, variantes, detalhes, uso, cuidados, foto_url, fotos, disponivel, sem_adicional, ativo, ordem, seo_titulo, seo_descricao, estoque, categoria, destaque, custo)
values ('altar-da-calma', 'Altar da Calma · Ametista', 'Exclusivo · Peça única', 'Duas drusas de ametista sobre a bandeja dourada: um altar de calma para o quarto ou a meditação.', 'A ametista é a pedra da calma, do sono tranquilo e da intuição. Os gregos a chamavam de amethystos, "não embriagado". Neste altar, duas drusas de ametista brasileira, com pontas violeta que guardam a luz, repousam sobre uma bandeja oval dourada.

Uma composição exclusiva da ARA, montada à mão: as pedras são naturais e esta combinação existe uma única vez.', 220, '', '[]'::jsonb, '[{"k": "Pedras", "v": "Duas drusas de ametista natural do Brasil"}, {"k": "Bandeja", "v": "Oval, de metal dourado"}, {"k": "Significado", "v": "Calma, proteção espiritual e intuição."}, {"k": "Exclusividade", "v": "Composição única, montada à mão pela ARA: não existe outra igual."}, {"k": "Foto", "v": "As fotos são do próprio altar que você vai receber."}]'::jsonb, 'Na mesa de cabeceira, no espaço de meditação ou no canto de leitura, onde bata uma luz suave.', 'Evite sol direto por muitas horas: a ametista desbota. Limpe com pincel macio ou pano seco.', '/img/loja/altar-da-calma.dd64cf51.jpg', '[]'::jsonb, true, true, true, 1, 'Altar da Calma: drusas de ametista na bandeja dourada | ARA', 'Duas drusas de ametista natural do Brasil sobre bandeja oval dourada: um altar de calma para o quarto ou a meditação. Peça única, montada à mão. Loja ARA.', 1, 'altar', true, 1 * coalesce((select custo from public.ara_produtos where slug = 'drusa-de-ametista'), 0) + 1 * coalesce((select custo from public.ara_produtos where slug = 'drusa-de-ametista-pequena'), 0) + 12)
on conflict (slug) do nothing;

insert into public.ara_produtos (slug, nome, tag, frase, texto, preco, rotulo, variantes, detalhes, uso, cuidados, foto_url, fotos, disponivel, sem_adicional, ativo, ordem, seo_titulo, seo_descricao, estoque, categoria, destaque, custo)
values ('altar-da-clareza', 'Altar da Clareza · Cristal de Quartzo', 'Exclusivo · Peça única', 'Três cristais de quartzo transparente sobre a bandeja dourada: clareza para a mente e para a casa.', 'O cristal de quartzo é a pedra mais clássica de todas. Transparente, é associado à clareza, à limpeza do ambiente e à força das intenções. Neste altar, três cristais de quartzo natural, entre eles uma ponta e um biterminado, com ponta nas duas extremidades, repousam sobre uma bandeja oval dourada.

Uma composição exclusiva da ARA, montada à mão: as pedras são naturais e esta combinação existe uma única vez.', 110, '', '[]'::jsonb, '[{"k": "Pedras", "v": "Três cristais de quartzo transparente natural"}, {"k": "Bandeja", "v": "Oval, de metal dourado"}, {"k": "Significado", "v": "Clareza, limpeza e amplificação das intenções."}, {"k": "Exclusividade", "v": "Composição única, montada à mão pela ARA: não existe outra igual."}, {"k": "Foto", "v": "As fotos são do próprio altar que você vai receber."}]'::jsonb, 'Na mesa de trabalho, no altar ou perto da janela, onde a luz atravessa os cristais.', 'Limpe com pincel macio ou pano úmido e seque bem. Evite quedas: as pontas podem lascar.', '/img/loja/altar-da-clareza.f4cbac4b.jpg', '[]'::jsonb, true, true, true, 2, 'Altar da Clareza: quartzo na bandeja dourada | ARA', 'Três cristais de quartzo transparente natural sobre bandeja oval dourada: um altar de clareza para a mesa ou a janela. Peça única, montada à mão. Loja ARA.', 1, 'altar', true, 1 * coalesce((select custo from public.ara_produtos where slug = 'cristal-de-quartzo'), 0) + 1 * coalesce((select custo from public.ara_produtos where slug = 'cristal-biterminado'), 0) + 1 * coalesce((select custo from public.ara_produtos where slug = 'ponta-de-cristal'), 0) + 12)
on conflict (slug) do nothing;

insert into public.ara_produtos (slug, nome, tag, frase, texto, preco, rotulo, variantes, detalhes, uso, cuidados, foto_url, fotos, disponivel, sem_adicional, ativo, ordem, seo_titulo, seo_descricao, estoque, categoria, destaque, custo)
values ('altar-do-equilibrio', 'Altar do Equilíbrio · 4 Cristais', 'Exclusivo · Peça única', 'Fluorita, lápis-lazúli, geodo e turmalina negra: quatro cristais, quatro intenções, numa só bandeja.', 'Um altar completo para quem quer começar: a fluorita verde para o foco, o lápis-lazúli para a sabedoria e a intuição, o geodo de cristais brancos para a harmonia da casa e a turmalina negra para a proteção. Os quatro repousam sobre uma bandeja oval dourada.

Uma composição exclusiva da ARA, montada à mão: as pedras são naturais e esta combinação existe uma única vez.', 230, '', '[]'::jsonb, '[{"k": "Pedras", "v": "Fluorita verde, lápis-lazúli, geodo de quartzo branco e turmalina negra"}, {"k": "Bandeja", "v": "Oval, de metal dourado"}, {"k": "Significado", "v": "Foco, sabedoria, harmonia e proteção."}, {"k": "Exclusividade", "v": "Composição única, montada à mão pela ARA: não existe outra igual."}, {"k": "Foto", "v": "As fotos são do próprio altar que você vai receber."}]'::jsonb, 'Na entrada da casa, na mesa de trabalho ou no altar. Se quiser, organize as pedras na ordem das suas intenções.', 'Limpe com pincel macio ou pano seco e não deixe de molho. A turmalina pode lascar com quedas.', '/img/loja/altar-do-equilibrio.e6218671.jpg', '["/img/loja/altar-do-equilibrio-2.b4e1aac0.jpg"]'::jsonb, true, true, true, 3, 'Altar do Equilíbrio: 4 cristais na bandeja dourada | ARA', 'Fluorita, lápis-lazúli, geodo e turmalina negra sobre bandeja oval dourada: foco, sabedoria, harmonia e proteção. Peça única, montada à mão. Loja ARA.', 1, 'altar', true, 1 * coalesce((select custo from public.ara_produtos where slug = 'fluorita-verde'), 0) + 1 * coalesce((select custo from public.ara_produtos where slug = 'geodo-marroquino'), 0) + 1 * coalesce((select custo from public.ara_produtos where slug = 'turmalina-negra-bruta'), 0) + 12)
on conflict (slug) do nothing;

insert into public.ara_produtos (slug, nome, tag, frase, texto, preco, rotulo, variantes, detalhes, uso, cuidados, foto_url, fotos, disponivel, sem_adicional, ativo, ordem, seo_titulo, seo_descricao, estoque, categoria, destaque, custo)
values ('altar-da-limpeza', 'Altar da Limpeza · Selenita e Ágata', 'Exclusivo · Peça única', 'Selenita e ágata sobre a bandeja dourada: a pedra que limpa e a pedra que equilibra.', 'A selenita é a pedra da limpeza energética: o nome vem de Selene, a deusa grega da lua. A ágata, aberta ao meio, mostra as camadas que se formaram ao longo de milhões de anos e traz equilíbrio e estabilidade. Juntas, sobre uma bandeja oval dourada, formam um altar para renovar o ambiente e os seus outros cristais.

Escolha a versão com bastão ou com placa hexagonal de selenita.

Uma composição exclusiva da ARA, montada à mão: as pedras são naturais e esta combinação existe uma única vez.', 190, 'Selenita', '[{"id": "bastao", "nome": "Com bastão de selenita", "preco": 190, "pedras": "bastão de selenita e ágata aberta ao meio", "img": "/img/loja/altar-da-limpeza-bastao.7a52dd5f.jpg"}, {"id": "placa", "nome": "Com placa hexagonal de selenita", "preco": 230, "pedras": "placa hexagonal de selenita e ágata aberta ao meio", "img": "/img/loja/altar-da-limpeza-placa.e7d54139.jpg"}]'::jsonb, '[{"k": "Pedras", "v": "Selenita natural e ágata aberta ao meio"}, {"k": "Bandeja", "v": "Oval, de metal dourado"}, {"k": "Significado", "v": "Limpeza, equilíbrio e estabilidade."}, {"k": "Exclusividade", "v": "Composição única, montada à mão pela ARA: não existe outra igual."}, {"k": "Foto", "v": "As fotos são do próprio altar que você vai receber."}]'::jsonb, 'Deixe os seus outros cristais, pulseiras e anéis ao lado da selenita por uma noite para renová-los.', 'A selenita se desfaz com água: nunca molhe. Limpe as pedras e a bandeja com pano seco.', '/img/loja/altar-da-limpeza-bastao.7a52dd5f.jpg', '["/img/loja/altar-da-limpeza-placa.e7d54139.jpg"]'::jsonb, true, true, true, 4, 'Altar da Limpeza: selenita e ágata na bandeja dourada | ARA', 'Selenita natural e ágata aberta ao meio sobre bandeja oval dourada: um altar para limpar e renovar os seus cristais. Peça única, montada à mão. Loja ARA.', 1, 'altar', true, 1 * coalesce((select custo from public.ara_produtos where slug = 'agata-in-natura'), 0) + 1 * coalesce((select custo from public.ara_produtos where slug = 'bastao-de-selenita'), 0) + 1 * coalesce((select custo from public.ara_produtos where slug = 'placa-de-selenita-hexagonal'), 0) + 12)
on conflict (slug) do nothing;

update public.ara_produtos set ativo = false, destaque = false, atualizado_em = now() where slug in ('agata-in-natura', 'bastao-de-selenita', 'cristal-biterminado', 'cristal-de-quartzo', 'drusa-de-ametista', 'drusa-de-ametista-pequena', 'fluorita-verde', 'geodo-marroquino', 'pirita-bruta', 'pirita-bruta-pequena', 'placa-de-selenita-hexagonal', 'ponta-de-cristal', 'turmalina-negra-bruta');
