-- Novos acessórios e o primeiro kit exclusivo da ARA (Kit Difusor de Pedra-Sabão), já à venda.
-- Itens da Alpha Tabacaria com a foto oficial; os demais com imagem ilustrativa até chegar a foto da peça.
insert into public.ara_produtos (slug, nome, categoria, tag, frase, texto, preco, detalhes, uso, cuidados, foto_url, disponivel, estoque, sem_adicional, ativo, ordem, seo_titulo, seo_descricao)
values
('kit-difusor-pedra-sabao', 'Kit Difusor de Pedra-Sabão', 'acessorio', 'Kit Exclusivo',
 'Difusor, velas e palo santo: o ritual completo para perfumar a casa.',
 E'Um kit montado pela ARA com tudo o que é preciso para começar: o difusor em pedra-sabão, um pacote de velas lamparina e 50 g de palo santo in natura.\n\nA pedra-sabão, tradicional do artesanato mineiro, segura o calor da vela, aquecendo devagar a água com algumas gotas de essência ou óleo essencial. Enquanto o aroma se espalha, acenda uma lasca de palo santo para limpar o ambiente e marcar o começo da pausa.\n\nUm presente pronto para quem cuida da casa como um lugar sagrado.',
 119,
 '[{"k": "Acompanha", "v": "Difusor de pedra-sabão, velas lamparina brancas (pacote com 6) e palo santo in natura (50 g)"}, {"k": "Material", "v": "Pedra-sabão"}, {"k": "Uso", "v": "Essências e óleos essenciais diluídos em água"}]',
 'Coloque água na cuba de cima e pingue de 3 a 5 gotas de essência ou óleo essencial. Acenda a vela lamparina e coloque-a na abertura da base. Antes de a água acabar, apague a vela. O palo santo: acenda a ponta de uma lasca, deixe a chama queimar por alguns segundos e apague, deixando a fumaça percorrer o ambiente.',
 'A pedra esquenta durante o uso: espere esfriar para tocar ou lavar. Não deixe a água secar com a vela acesa. Mantenha longe de cortinas, crianças e animais.',
 null,
 true, null, true, true, 5,
 'Kit Difusor de Pedra-Sabão com velas e palo santo | Loja ARA',
 'Kit exclusivo ARA: difusor aromatizador em pedra-sabão, velas lamparina e palo santo in natura 50 g. Tudo para perfumar e limpar a energia da casa.'),
('lakshmi-branca', 'Lakshmi Branca', 'acessorio', 'Novo',
 'A deusa da prosperidade e da abundância, para o altar da casa.',
 E'Na tradição hindu, Lakshmi é a deusa da prosperidade, da abundância e da beleza. É representada sentada ou de pé sobre uma flor de lótus, símbolo de pureza, e é lembrada em casa e no trabalho para atrair fartura e harmonia.\n\nEm acabamento branco, a imagem traz a serenidade da deusa para o altar, a sala ou a mesa de trabalho.',
 100,
 '[{"k": "Acabamento", "v": "Branco"}, {"k": "Origem", "v": "Importada"}, {"k": "Tradição", "v": "Hindu"}]',
 'Na tradição, Lakshmi fica em um lugar limpo e elevado, voltada para a entrada da casa ou perto de onde se guarda o dinheiro. Combina com um cristal de prosperidade, como o citrino ou a pirita.',
 'Limpe com pano seco e macio, sem produtos abrasivos.',
 'https://images.tcdn.com.br/img/img_prod/1211384/lakshmi_branco_539_1_a415e6f5b1aa5bbac20a5f4c962c18fc.png',
 true, null, true, true, 11,
 'Imagem de Lakshmi Branca, deusa da prosperidade | Loja ARA',
 'Imagem da deusa hindu Lakshmi em acabamento branco, símbolo de prosperidade e abundância, para o altar ou a mesa de trabalho. Loja ARA.'),
('incensario-caixa-de-madeira', 'Incensário Caixa de Madeira', 'acessorio', 'Novo',
 'O incenso de todo dia, sem cinza espalhada pelo altar.',
 E'Um incensário em forma de caixa de madeira, que recolhe as cinzas e deixa o ritual do incenso organizado.\n\nÉ a escolha para quem gosta de incenso todos os dias e quer o altar sempre arrumado.',
 80,
 '[{"k": "Material", "v": "Madeira"}, {"k": "Formato", "v": "Caixa"}, {"k": "Uso", "v": "Incensos em vareta"}]',
 'Encaixe a vareta acesa no apoio do incensário e deixe a cinza cair dentro da caixa.',
 'Esvazie as cinzas depois de cada uso e limpe com pano seco. Use sobre uma superfície que não pegue fogo.',
 'https://images.tcdn.com.br/img/img_prod/1211384/inscensario_caixa_madeira_579_1_79da818b3af53c61da7db06822b23ee6.jpg',
 true, null, true, true, 12,
 'Incensário Caixa de Madeira, porta-incenso | Loja ARA',
 'Incensário em caixa de madeira que recolhe as cinzas e deixa o ritual do incenso organizado. Para incensos em vareta. Loja ARA.'),
('incensario-feng-shui', 'Incensário Feng Shui', 'acessorio', 'Novo',
 'Um apoio para o incenso, no espírito do Feng Shui.',
 E'No Feng Shui, o incenso movimenta a energia do ambiente e ajuda a renovar o que ficou parado. Este incensário dá ao ritual um lugar bonito na casa, com o equilíbrio e a simplicidade da tradição oriental.\n\nCombina com o altar, a mesa de meditação ou a entrada da casa.',
 60,
 '[{"k": "Marca", "v": "Feng-Shui"}, {"k": "Uso", "v": "Incensos em vareta"}, {"k": "Tradição", "v": "Feng Shui"}]',
 'Encaixe a vareta acesa no apoio e deixe a cinza cair no incensário.',
 'Esvazie as cinzas depois de cada uso e limpe com pano seco. Use sobre uma superfície que não pegue fogo.',
 'https://images.tcdn.com.br/img/img_prod/1211384/incensario_feng_shui_601_1_61ed0f1ed1c6a8865bbcd7e6e0ccba17.jpeg',
 true, null, true, true, 13,
 'Incensário Feng Shui para incenso de vareta | Loja ARA',
 'Incensário Feng Shui para incensos de vareta: o ritual do incenso com o equilíbrio da tradição oriental, para o altar ou a meditação. Loja ARA.'),
('ampulheta-5-minutos', 'Ampulheta 5 Minutos', 'acessorio', 'Novo',
 'Cinco minutos de areia para uma pausa de verdade.',
 E'Vire a ampulheta e dê a você cinco minutos: para respirar, meditar, alongar ou só ficar em silêncio.\n\nSem tela e sem alarme, a areia marca o tempo devagar, e fica bonita na mesa, no altar ou na estante.',
 75,
 '[{"k": "Tempo", "v": "5 minutos"}, {"k": "Uso", "v": "Meditação, respiração e pausas"}]',
 'Vire a ampulheta no começo da sua pausa e acompanhe a areia até o fim. Cinco minutos de respiração consciente por dia já fazem diferença.',
 'Limpe com pano seco. Evite quedas e sol forte direto.',
 'https://images.tcdn.com.br/img/img_prod/1211384/ampulheta_5_minutos_1219_1_a81da87e387a047ebc0c00d36d9697f9.jpg',
 true, null, true, true, 14,
 'Ampulheta 5 minutos para meditação | Loja ARA',
 'Ampulheta de 5 minutos para meditação, respiração e pausas sem tela. Peça para a mesa, o altar ou a estante. Loja ARA.'),
('incenso-parimal-jardim-nag-champa', 'Incenso Parimal Jardim Nag Champa', 'acessorio', 'Novo',
 'O aroma clássico dos templos da Índia.',
 E'O Nag Champa é um dos aromas mais tradicionais da Índia: une a flor de champaca e o sândalo em uma massa de resinas, com perfume doce, amadeirado e envolvente.\n\nÉ o incenso dos templos e das salas de meditação, para acender no início de uma prática ou para deixar a casa com cheiro de calma.',
 60,
 '[{"k": "Marca", "v": "Parimal"}, {"k": "Aroma", "v": "Nag Champa"}, {"k": "Origem", "v": "Índia"}]',
 'Acenda a ponta, deixe a chama queimar por alguns segundos e apague com um sopro leve. Use sempre um incensário.',
 'Mantenha longe de cortinas, crianças e animais. Não deixe aceso sem ninguém por perto.',
 'https://images.tcdn.com.br/img/img_prod/1211384/parimal_jardim_nag_champa_607_1_9808fa1de6fc5288248d1ea4d5bd70fd.png',
 true, null, true, true, 15,
 'Incenso Nag Champa Parimal Jardim indiano | Loja ARA',
 'Incenso indiano Parimal Jardim Nag Champa, aroma clássico de champaca e sândalo dos templos da Índia. Para meditação e para perfumar a casa. Loja ARA.'),
('incensario-regua-dos-chakras', 'Incensário Régua dos Chakras', 'acessorio', 'Novo',
 'Os sete chakras em uma régua de madeira para o seu incenso.',
 E'Um incensário de madeira no formato de régua, com os sete chakras ao longo da peça, da raiz ao topo da cabeça.\n\nA vareta encaixa na ponta e a cinza cai sobre a madeira, sem sujar o móvel. Uma peça simples para a meditação e o altar.',
 29,
 '[{"k": "Material", "v": "Madeira"}, {"k": "Comprimento", "v": "25 cm"}, {"k": "Uso", "v": "Incensos em vareta"}]',
 'Encaixe a vareta acesa no apoio da ponta, inclinada sobre a régua, para que a cinza caia sobre a madeira.',
 'Esvazie as cinzas depois de cada uso e limpe com pano seco. Use sobre uma superfície que não pegue fogo.',
 null,
 true, null, true, true, 16,
 'Incensário Régua dos Chakras em madeira 25 cm | Loja ARA',
 'Incensário de madeira tipo régua, 25 cm, com os sete chakras: apoio para incenso de vareta que recolhe a cinza. Loja ARA.'),
('incensario-canaleta-de-bambu', 'Incensário Canaleta de Bambu', 'acessorio', 'Novo',
 'Bambu natural, leve e simples, para o incenso de todo dia.',
 E'Uma canaleta de bambu natural que serve de apoio para o incenso e recolhe as cinzas ao longo da peça.\n\nLeve e rústica, combina com a mesa de meditação, o altar ou a varanda.',
 25,
 '[{"k": "Material", "v": "Bambu natural"}, {"k": "Uso", "v": "Incensos em vareta"}]',
 'Encaixe a vareta acesa no apoio da ponta, inclinada sobre a canaleta, para que a cinza caia dentro dela.',
 'Esvazie as cinzas depois de cada uso e limpe com pano seco. Use sobre uma superfície que não pegue fogo.',
 null,
 true, null, true, true, 17,
 'Incensário Canaleta de Bambu natural | Loja ARA',
 'Incensário canaleta de bambu natural para incenso de vareta, recolhe a cinza ao longo da peça. Leve e rústico. Loja ARA.'),
('palo-santo-50g', 'Palo Santo In Natura 50 g', 'acessorio', 'Novo',
 'A madeira sagrada dos Andes, para limpar e perfumar o ambiente.',
 E'O palo santo, "madeira sagrada" em espanhol, é uma árvore da costa do Pacífico na América do Sul, usada há séculos pelos povos andinos em rituais de limpeza e de proteção.\n\nIn natura, em lascas de madeira, ele solta uma fumaça de aroma doce, cítrico e amadeirado. Acenda ao começar uma meditação, ao arrumar a casa ou para renovar o ambiente.',
 39,
 '[{"k": "Peso", "v": "50 g"}, {"k": "Tipo", "v": "Lascas de madeira in natura"}, {"k": "Origem", "v": "América do Sul"}]',
 'Acenda a ponta de uma lasca, deixe a chama queimar por 30 segundos e apague. Passe a fumaça pelos cantos do ambiente e apoie a lasca em um incensário ou prato de cerâmica até apagar.',
 'Mantenha longe de cortinas, crianças e animais. Não deixe aceso sem ninguém por perto. Guarde em local seco.',
 null,
 true, null, true, true, 18,
 'Palo Santo in natura 50 g, madeira sagrada | Loja ARA',
 'Palo santo in natura, 50 g em lascas de madeira: a madeira sagrada dos Andes para limpeza energética e para perfumar a casa. Loja ARA.'),
('vela-lamparina-branca', 'Vela Lamparina Branca, pacote com 6', 'acessorio', 'Novo',
 'Velinhas para o difusor, o altar e a meditação.',
 E'Velas lamparina brancas em copinho de alumínio, do tamanho certo para difusores e rechauds.\n\nTambém iluminam o altar, a mesa de meditação ou o banho, com uma chama pequena e tranquila.',
 15,
 '[{"k": "Quantidade", "v": "6 velas"}, {"k": "Cor", "v": "Branca"}, {"k": "Uso", "v": "Difusores, rechauds e altar"}]',
 'Acenda sobre uma superfície plana que não pegue fogo ou dentro do difusor.',
 'Não deixe acesa sem ninguém por perto. Mantenha longe de cortinas, crianças e animais.',
 null,
 true, null, true, true, 19,
 'Vela lamparina branca, pacote com 6 | Loja ARA',
 'Velas lamparina brancas em copinho de alumínio, pacote com 6, para difusores, rechauds, altar e meditação. Loja ARA.')
on conflict (slug) do nothing;
