-- Novos acessórios e complementos, já à venda. Entram ocultos; a publicação do site os ativa.
insert into public.ara_produtos (slug, nome, categoria, tag, frase, texto, preco, detalhes, uso, cuidados, disponivel, estoque, sem_adicional, ativo, ordem, seo_titulo, seo_descricao)
values
('mensageiro-do-vento', 'Mensageiro do Vento', 'acessorio', 'Novo',
 'O vento passa, e a casa responde com um som leve.',
 E'O mensageiro do vento é usado há séculos nas tradições do Oriente para marcar a passagem do vento pela casa. No Feng Shui, ele fica em portas, janelas e varandas para movimentar a energia do ambiente e afastar o que pesa.\n\nPendure onde bata uma brisa: cada sopro vira um som suave, um convite para uma pausa.',
 129,
 '[{"k":"Uso","v":"Portas, janelas e varandas cobertas"},{"k":"Tradição","v":"Feng Shui e tradições do Oriente"}]',
 'Pendure em um lugar com circulação de ar, como a entrada da casa, uma janela ou a varanda. No Feng Shui, a entrada é o lugar mais indicado.',
 'Em área externa, prefira um lugar coberto. Limpe com pano seco.',
 true, null, true, false, 7,
 'Mensageiro do Vento para casa e Feng Shui | Loja ARA',
 'Mensageiro do vento para portas, janelas e varandas, usado no Feng Shui para movimentar a energia da casa. Peça selecionada pela ARA, com envio para todo o Brasil.'),
('mini-ganesh-dourado', 'Mini Ganesh Dourado', 'acessorio', 'Novo',
 'O senhor dos começos, em tamanho de altar.',
 E'Na tradição hindu, Ganesh é o senhor dos começos e o removedor de obstáculos: é lembrado antes de toda nova jornada, de uma viagem a um negócio. Também é associado à sabedoria e à prosperidade.\n\nEm versão mini e dourada, cabe no altar, na mesa de trabalho ou na entrada da casa.',
 99,
 '[{"k":"Acabamento","v":"Dourado"},{"k":"Tamanho","v":"Mini, para altar e mesa"},{"k":"Tradição","v":"Hindu"}]',
 'Na tradição, Ganesh fica perto da entrada da casa ou no lugar onde começam os projetos, como a mesa de trabalho. Combina com um cristal de prosperidade, como o citrino ou a pirita.',
 'Limpe com pano seco e macio, sem produtos abrasivos, para preservar o dourado.',
 true, null, true, false, 8,
 'Mini Ganesh Dourado para altar e mesa | Loja ARA',
 'Mini Ganesh dourado, o removedor de obstáculos e senhor dos começos na tradição hindu. Para o altar, a mesa de trabalho ou a entrada da casa. Loja ARA.'),
('incenso-shankar-massala', 'Incenso Shankar Massala', 'acessorio', 'Novo',
 'Incenso indiano artesanal, de queima lenta e aroma que fica.',
 E'A Shankar produz incensos artesanais na Índia desde 1964. O massala é feito de uma massa de resinas, ervas, especiarias e óleos essenciais enrolada na vareta: por isso o aroma é mais rico e duradouro, com menos fumaça que os incensos comuns.\n\nAcenda no início de uma meditação, ao arrumar a casa ou para fechar o dia.',
 19,
 '[{"k":"Marca","v":"Shankar, Índia"},{"k":"Tipo","v":"Massala, em varetas"},{"k":"Aroma","v":"Consulte os aromas disponíveis pelo WhatsApp"}]',
 'Acenda a ponta, deixe a chama queimar por alguns segundos e apague com um sopro leve. Use sempre um incensário.',
 'Mantenha longe de cortinas, crianças e animais. Não deixe aceso sem ninguém por perto.',
 true, null, true, false, 9,
 'Incenso Shankar Massala indiano artesanal | Loja ARA',
 'Incenso indiano Shankar massala, artesanal, feito de resinas, ervas e óleos essenciais: aroma duradouro e menos fumaça. Loja ARA.'),
('incenso-nii', 'Incenso Nii', 'acessorio', 'Novo',
 'Aroma para marcar o início de uma pausa.',
 E'Incenso em varetas para perfumar a casa e marcar os seus momentos de pausa: uma meditação, um banho demorado, o fim do dia.\n\nAcenda, respire e deixe o aroma ocupar o ambiente.',
 19,
 '[{"k":"Tipo","v":"Varetas"},{"k":"Aroma","v":"Consulte os aromas disponíveis pelo WhatsApp"}]',
 'Acenda a ponta, deixe a chama queimar por alguns segundos e apague com um sopro leve. Use sempre um incensário.',
 'Mantenha longe de cortinas, crianças e animais. Não deixe aceso sem ninguém por perto.',
 true, null, true, false, 10,
 'Incenso Nii em varetas | Loja ARA',
 'Incenso Nii em varetas para perfumar a casa e marcar os momentos de pausa e meditação. Loja ARA, envio para todo o Brasil.')
on conflict (slug) do nothing;
