-- Pedras da planilha de compra de 01/10/2026, cada uma com a foto da própria peça em fundo branco.
-- Preço: o sugerido da planilha (custo real x 3) arredondado para cima, conforme a régua do dono (ver CLAUDE.md).
-- As pedras que estavam com ilustração viram peças reais; Quartzo Rosa Bruto e Drusa de Citrino, que não vieram na compra,
-- são reaproveitados como Cristal de Quartzo e Pulseira de Citrino (os endereços antigos redirecionam).
update public.ara_produtos set preco=120, estoque=1, disponivel=true, ativo=true, foto_url='/img/loja/drusa-de-ametista.3637a115.jpg', ordem=0, detalhes='[{"k": "Pedra", "v": "Ametista natural (quartzo violeta)"}, {"k": "Formato", "v": "Drusa bruta"}, {"k": "Origem", "v": "Brasil"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]', atualizado_em=now() where slug='drusa-de-ametista';
update public.ara_produtos set preco=60, estoque=2, disponivel=true, ativo=true, foto_url='/img/loja/pirita-bruta.f59ee832.jpg', ordem=9, detalhes='[{"k": "Pedra", "v": "Pirita natural"}, {"k": "Formato", "v": "Bruta"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]', atualizado_em=now() where slug='pirita-bruta';
update public.ara_produtos set preco=30, estoque=1, disponivel=true, ativo=true, foto_url='/img/loja/ponta-de-cristal.5571af42.jpg', ordem=13, detalhes='[{"k": "Pedra", "v": "Quartzo transparente natural (cristal)"}, {"k": "Formato", "v": "Ponta bruta"}, {"k": "Origem", "v": "Brasil"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]', atualizado_em=now() where slug='ponta-de-cristal';
update public.ara_produtos set preco=40, estoque=1, disponivel=true, ativo=true, foto_url='/img/loja/turmalina-negra-bruta.7506b5c1.jpg', ordem=8, detalhes='[{"k": "Pedra", "v": "Turmalina negra natural (schorlita)"}, {"k": "Formato", "v": "Bruta, em bastão"}, {"k": "Origem", "v": "Brasil"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]', atualizado_em=now() where slug='turmalina-negra-bruta';
update public.ara_produtos set slug='cristal-de-quartzo', nome='Cristal de Quartzo', categoria='cristal', tag='Peça única', frase='O quartzo transparente, a pedra mais clássica de todas.', texto=E'Um cristal de quartzo transparente, com as faces naturais da pedra. O Brasil é um dos maiores produtores de quartzo do mundo.\n\nA palavra cristal vem do grego krýstallos, "gelo": os gregos acreditavam que o quartzo era gelo que nunca derretia. Na tradição dos cristais, é a pedra da clareza, que amplifica a energia das outras.', preco=30, detalhes='[{"k": "Pedra", "v": "Quartzo transparente natural (cristal)"}, {"k": "Origem", "v": "Brasil"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]', uso='Sobre a mesa, no altar ou junto de outros cristais, onde a luz possa atravessar a pedra.', cuidados='Pode ir à água corrente. Seque bem e evite quedas, que lascam as pontas.', foto_url='/img/loja/cristal-de-quartzo.22e8c72c.jpg', disponivel=true, estoque=1, sem_adicional=true, ativo=true, ordem=11, seo_titulo='Cristal de Quartzo transparente natural | Loja ARA', seo_descricao='Cristal de quartzo transparente natural do Brasil, a pedra da clareza na tradição dos cristais. Peça única. Loja ARA.', atualizado_em=now() where slug='quartzo-rosa-bruto';
update public.ara_produtos set slug='pulseira-de-citrino', nome='Pulseira de Citrino', categoria='acessorio', tag='Prosperidade', frase='Lascas de citrino em tons de mel, para usar no pulso.', texto=E'Uma pulseira de lascas de citrino, em tons de mel e âmbar, montada em fio elástico.\n\nNa tradição dos cristais, o citrino é a pedra da prosperidade, da alegria e da energia para começar projetos. No pulso, ele acompanha você o dia todo.', preco=120, detalhes='[{"k": "Pedra", "v": "Citrino, em lascas"}, {"k": "Formato", "v": "Pulseira em fio elástico"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]', uso='Use no dia a dia. Para colocar, role a pulseira pela mão em vez de esticar o fio.', cuidados='Tire para tomar banho e evite perfume e cremes. Limpe com pano seco.', foto_url='/img/loja/pulseira-de-citrino.9541da5a.jpg', disponivel=true, estoque=1, sem_adicional=true, ativo=true, ordem=27, seo_titulo='Pulseira de Citrino natural | Loja ARA', seo_descricao='Pulseira de lascas de citrino em tons de mel, em fio elástico. A pedra da prosperidade, para usar no pulso. Loja ARA.', atualizado_em=now() where slug='drusa-de-citrino';
insert into public.ara_produtos (slug, nome, categoria, tag, frase, texto, preco, detalhes, uso, cuidados, foto_url, disponivel, estoque, sem_adicional, ativo, ordem, seo_titulo, seo_descricao)
values
('agata-in-natura', 'Ágata In Natura', 'cristal', 'Peça única',
 'Um geodo aberto ao meio, com as camadas da ágata à mostra.',
 E'A ágata se forma em camadas, dentro de cavidades nas rochas vulcânicas, ao longo de milhões de anos. Aberta ao meio, mostra os anéis de cor e o interior cristalizado, cada um com um desenho que não se repete.\n\nNa tradição dos cristais, a ágata é a pedra do equilíbrio e da estabilidade. O Rio Grande do Sul é um dos maiores produtores de ágata do mundo.',
 110, '[{"k": "Pedra", "v": "Ágata natural"}, {"k": "Formato", "v": "In natura, aberta ao meio"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]',
 'Na estante, na mesa de centro ou no altar, com as duas metades lado a lado ou uma de frente para a outra.',
 'Limpe com pincel macio ou pano úmido e seque bem.',
 '/img/loja/agata-in-natura.622d5a71.jpg', true, 1, true, true, 2,
 'Ágata In Natura, geodo aberto | Loja ARA',
 'Ágata in natura aberta ao meio, com as camadas e o interior cristalizado à mostra. Peça única, a pedra do equilíbrio. Loja ARA.'),
('agata-marrom-com-base', 'Ágata Marrom com Base', 'cristal', 'Peça única',
 'Uma chapa de ágata em tons de terra, pronta para expor.',
 E'Uma fatia de ágata em tons de marrom e caramelo, com os veios naturais da pedra, apoiada em uma base para ficar de pé.\n\nNa tradição dos cristais, a ágata traz equilíbrio e estabilidade. Os tons terrosos combinam com a mesa de trabalho e a estante.',
 40, '[{"k": "Pedra", "v": "Ágata natural, tons de marrom"}, {"k": "Formato", "v": "Chapa com base"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]',
 'Na mesa de trabalho, na estante ou perto de uma janela, onde a luz passa pelos veios.',
 'Limpe com pincel macio ou pano seco.',
 '/img/loja/agata-marrom-com-base.a600d98d.jpg', true, 1, true, true, 3,
 'Ágata Marrom com Base | Loja ARA',
 'Chapa de ágata natural em tons de marrom, com base para expor. Peça única, a pedra do equilíbrio. Loja ARA.'),
('chaveiro-de-amazonita', 'Chaveiro de Amazonita', 'acessorio', 'Peça única',
 'O verde-água da pedra da coragem, junto das suas chaves.',
 E'A amazonita tem um verde-água suave, às vezes com veios brancos. O nome vem do rio Amazonas.\n\nNa tradição dos cristais, é a pedra da coragem, da comunicação e da harmonia. No chaveiro, ela acompanha você todos os dias.',
 60, '[{"k": "Pedra", "v": "Amazonita natural"}, {"k": "Formato", "v": "Pingente com argola de chaveiro"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]',
 'Leve com as chaves de casa ou do carro, ou pendure na bolsa.',
 'Evite quedas e contato com perfume e produtos de limpeza. Limpe com pano seco.',
 '/img/loja/chaveiro-de-amazonita.0bbda274.jpg', true, 1, true, true, 28,
 'Chaveiro de Amazonita natural | Loja ARA',
 'Chaveiro com pedra de amazonita natural, verde-água, a pedra da coragem e da harmonia. Peça única. Loja ARA.'),
('chaveiro-de-ametista-escura', 'Chaveiro de Ametista Escura', 'acessorio', 'Peça única',
 'A ametista em tom violeta profundo, para levar com você.',
 E'Um pingente de ametista em violeta intenso, preso a uma argola de chaveiro.\n\nNa tradição dos cristais, a ametista é a pedra da calma e da proteção. O nome vem do grego amethystos, "não embriagado": os gregos acreditavam que ela mantinha a mente clara.',
 50, '[{"k": "Pedra", "v": "Ametista natural, tom escuro"}, {"k": "Formato", "v": "Pingente com argola de chaveiro"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]',
 'Leve com as chaves de casa ou do carro, ou pendure na bolsa.',
 'Evite sol direto por muitas horas, que pode desbotar a cor. Evite quedas e contato com perfume e produtos de limpeza. Limpe com pano seco.',
 '/img/loja/chaveiro-de-ametista-escura.1c9ae8ed.jpg', true, 1, true, true, 29,
 'Chaveiro de Ametista escura natural | Loja ARA',
 'Chaveiro com pingente de ametista natural em violeta profundo, a pedra da calma e da proteção. Peça única. Loja ARA.'),
('chaveiro-de-ametista-clara', 'Chaveiro de Ametista Clara', 'acessorio', 'Peça única',
 'A ametista em lilás suave, para levar com você.',
 E'Um pingente de ametista em tom lilás claro, preso a uma argola de chaveiro.\n\nNa tradição dos cristais, a ametista é a pedra da calma e da proteção, e os tons claros têm a delicadeza da lavanda.',
 40, '[{"k": "Pedra", "v": "Ametista natural, tom claro"}, {"k": "Formato", "v": "Pingente com argola de chaveiro"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]',
 'Leve com as chaves de casa ou do carro, ou pendure na bolsa.',
 'Evite sol direto por muitas horas, que pode desbotar a cor. Evite quedas e contato com perfume e produtos de limpeza. Limpe com pano seco.',
 '/img/loja/chaveiro-de-ametista-clara.2c2ceb0a.jpg', true, 1, true, true, 30,
 'Chaveiro de Ametista clara natural | Loja ARA',
 'Chaveiro com pingente de ametista natural em lilás suave, a pedra da calma e da proteção. Peça única. Loja ARA.'),
('cristal-biterminado', 'Cristal Biterminado', 'cristal', 'Peça única',
 'Um cristal com ponta nas duas extremidades.',
 E'O cristal biterminado é o quartzo que cresceu livre, sem se prender à rocha, e por isso formou uma ponta em cada extremidade.\n\nNa tradição dos cristais, as duas pontas fazem a energia circular nos dois sentidos: é usado para equilibrar e conectar.',
 30, '[{"k": "Pedra", "v": "Quartzo transparente natural"}, {"k": "Formato", "v": "Biterminado, com duas pontas"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]',
 'Na mão durante a meditação, sobre a mesa ou entre dois outros cristais, ligando um ao outro.',
 'Pode ir à água corrente. Seque bem e evite quedas, que lascam as pontas.',
 '/img/loja/cristal-biterminado.ee459530.jpg', true, 1, true, true, 12,
 'Cristal Biterminado de quartzo natural | Loja ARA',
 'Cristal de quartzo biterminado, com ponta nas duas extremidades, usado para equilibrar e conectar. Peça única. Loja ARA.'),
('drusa-de-ametista-pequena', 'Drusa de Ametista Pequena', 'cristal', 'Peça única',
 'Pontas violeta reunidas, em tamanho para a mesa ou o altar.',
 E'Uma drusa de ametista em tamanho compacto: pequenas pontas de cristal violeta que nascem juntas, dentro dos geodos do sul do Brasil.\n\nNa tradição dos cristais, a ametista é a pedra da calma, do sono tranquilo e da proteção.',
 80, '[{"k": "Pedra", "v": "Ametista natural (quartzo violeta)"}, {"k": "Formato", "v": "Drusa bruta, pequena"}, {"k": "Origem", "v": "Brasil"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]',
 'Na mesa de cabeceira, no altar ou na mesa de trabalho, onde bata luz natural.',
 'Evite sol direto por muitas horas, que pode desbotar a cor. Limpe com pincel macio ou pano seco.',
 '/img/loja/drusa-de-ametista-pequena.a6eafcf4.jpg', true, 1, true, true, 1,
 'Drusa de Ametista pequena natural | Loja ARA',
 'Drusa de ametista natural do Brasil em tamanho pequeno, para a mesa ou o altar. A pedra da calma. Peça única. Loja ARA.'),
('fluorita-verde', 'Fluorita Verde', 'cristal', 'Peça única',
 'O verde translúcido da pedra da concentração.',
 E'A fluorita é um cristal translúcido que aparece em verde, roxo e azul. Sob luz ultravioleta, ela brilha: foi ela que deu nome ao fenômeno da fluorescência.\n\nNa tradição dos cristais, a fluorita verde é a pedra da concentração e da organização das ideias, querida por quem estuda e trabalha.',
 30, '[{"k": "Pedra", "v": "Fluorita verde natural"}, {"k": "Formato", "v": "Bruta"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]',
 'Na mesa de estudo ou de trabalho, perto do computador.',
 'É uma pedra macia, que risca com facilidade: guarde separada e evite água. Limpe com pano seco.',
 '/img/loja/fluorita-verde.0b09fe93.jpg', true, 1, true, true, 14,
 'Fluorita Verde bruta natural | Loja ARA',
 'Fluorita verde natural bruta, translúcida, a pedra da concentração e do estudo na tradição dos cristais. Peça única. Loja ARA.'),
('geodo-marroquino', 'Geodo Marroquino', 'cristal', 'Peça única',
 'Uma pedra que guarda cristais por dentro.',
 E'O geodo é uma pedra oca: por fora, uma casca rústica; por dentro, uma cavidade forrada de pequenos cristais que se formaram ao longo de milhões de anos. Este vem do Marrocos.\n\nNa tradição dos cristais, o geodo é símbolo do que guardamos de mais bonito por dentro.',
 60, '[{"k": "Pedra", "v": "Geodo natural"}, {"k": "Origem", "v": "Marrocos"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]',
 'Na estante, na mesa de centro ou no altar, com a parte aberta virada para a luz.',
 'Limpe com pincel macio ou pano seco.',
 '/img/loja/geodo-marroquino.95ad4731.jpg', true, 1, true, true, 4,
 'Geodo Marroquino natural | Loja ARA',
 'Geodo natural do Marrocos, pedra rústica por fora e forrada de cristais por dentro. Peça única. Loja ARA.'),
('geodo-branco', 'Geodo Branco', 'cristal', 'Peça única',
 'Uma cavidade de cristais brancos, como neve dentro da pedra.',
 E'Um geodo de quartzo branco: a pedra se abriu e mostra uma cavidade forrada de pequenos cristais claros, que se formaram ao longo de milhões de anos.\n\nNa tradição dos cristais, o quartzo branco é associado à limpeza e à paz.',
 50, '[{"k": "Pedra", "v": "Geodo de quartzo branco natural"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]',
 'Na estante, na mesa de centro ou no altar, com a parte aberta virada para a luz.',
 'Limpe com pincel macio ou pano seco.',
 '/img/loja/geodo-branco.54022ac1.jpg', true, 1, true, true, 5,
 'Geodo Branco de quartzo natural | Loja ARA',
 'Geodo de quartzo branco natural, com uma cavidade forrada de pequenos cristais. Peça única. Loja ARA.'),
('pirita-bruta-pequena', 'Pirita Bruta Pequena', 'cristal', 'Peça única',
 'O brilho dourado da prosperidade, em tamanho de bolso.',
 E'Uma pirita bruta em tamanho pequeno, com o brilho metálico que lhe deu o apelido de ouro dos tolos.\n\nNa tradição dos cristais, a pirita é associada à prosperidade e à abundância. Cabe na carteira, no caixa ou na mesa de trabalho.',
 40, '[{"k": "Pedra", "v": "Pirita natural"}, {"k": "Formato", "v": "Bruta, pequena"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]',
 'Na carteira, no caixa, na mesa de trabalho ou ao lado do citrino.',
 'Mantenha longe da água e da umidade, que tiram o brilho. Limpe só com pano seco.',
 '/img/loja/pirita-bruta-pequena.bac9aefd.jpg', true, 1, true, true, 10,
 'Pirita bruta pequena natural | Loja ARA',
 'Pirita bruta natural pequena, de brilho metálico, a pedra da prosperidade na tradição dos cristais. Peça única. Loja ARA.'),
('bastao-de-selenita', 'Bastão de Selenita', 'cristal', 'Limpeza',
 'A pedra branca que limpa as energias dos outros cristais.',
 E'A selenita é um cristal branco e acetinado, de brilho que lembra a luz da lua: o nome vem de Selene, a deusa grega da lua.\n\nNa tradição dos cristais, ela é a pedra da limpeza energética. Em bastão, é usada para passar pelo corpo e pelo ambiente, ou deitada ao lado de outros cristais para renová-los.',
 60, '[{"k": "Pedra", "v": "Selenita natural"}, {"k": "Formato", "v": "Bastão"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]',
 'Deite os outros cristais ao lado do bastão por uma noite para limpá-los, ou passe o bastão pelo ambiente.',
 'A selenita se desfaz com água: nunca molhe. Limpe com pano seco e evite quedas.',
 '/img/loja/bastao-de-selenita.51c0bb4d.jpg', true, 1, true, true, 7,
 'Bastão de Selenita natural | Loja ARA',
 'Bastão de selenita natural, o cristal branco da limpeza energética, usado para renovar os outros cristais. Peça única. Loja ARA.'),
('placa-de-selenita-hexagonal', 'Placa de Selenita Hexagonal', 'cristal', 'Limpeza',
 'Uma base de selenita para limpar e carregar os seus cristais.',
 E'Uma placa de selenita em forma de hexágono, branca e acetinada, com o brilho que lembra a luz da lua.\n\nNa tradição dos cristais, a selenita é a pedra da limpeza energética: os outros cristais, as pulseiras e as joias ficam sobre a placa para serem renovados.',
 100, '[{"k": "Pedra", "v": "Selenita natural"}, {"k": "Formato", "v": "Placa hexagonal"}, {"k": "Observação", "v": "Peça natural: a foto é da própria pedra que você vai receber."}]',
 'Deixe os seus cristais, pulseiras e anéis sobre a placa por uma noite.',
 'A selenita se desfaz com água: nunca molhe. Limpe com pano seco e evite quedas.',
 '/img/loja/placa-de-selenita-hexagonal.a79a5643.jpg', true, 1, true, true, 6,
 'Placa de Selenita Hexagonal para limpar cristais | Loja ARA',
 'Placa de selenita natural hexagonal, para limpar e carregar cristais, pulseiras e joias. Peça única. Loja ARA.')
on conflict (slug) do nothing;
