-- Incensos ganham categoria própria na loja (antes ficavam em "acessórios").
-- O Shankar Massala, que tinha os aromas como opções com a quantidade digitada no campo errado,
-- vira um produto por aroma, cada um com o seu estoque e a foto da caixa (Kalan Presentes).
-- Nag Champa aparecia duas vezes ("Nagchampa" e "Nag Champa"): virou um só, com 2 unidades.
-- Citronela não tem foto na Kalan: usa a foto que o dono subiu do Shankar.
-- Novo: Isqueiro BIC Maxi, R$ 15, oferecido junto com os incensos.
alter table public.ara_produtos drop constraint if exists ara_produtos_categoria_chk;
alter table public.ara_produtos add constraint ara_produtos_categoria_chk check (categoria = any (array['cristal','incenso','acessorio']));

update public.ara_produtos set categoria = 'incenso', atualizado_em = now() where slug like 'incenso-%';

insert into public.ara_produtos (slug,nome,categoria,preco,custo,estoque,disponivel,ativo,sem_adicional,ordem,tag,frase,texto,detalhes,uso,cuidados,foto_url,fotos,variantes,rotulo,seo_titulo,seo_descricao)
values
('incenso-shankar-nag-champa','Incenso Shankar Massala Nag Champa','incenso',10,3.67,2,true,true,true,20,'Novo','Champaca e sândalo: o aroma clássico dos templos da Índia.','A Shankar produz incensos artesanais na Índia desde 1964. O massala é feito de uma massa de resinas, ervas, especiarias e óleos essenciais enrolada na vareta: por isso o aroma é mais rico e duradouro, com menos fumaça que os incensos comuns.

Acenda no início de uma meditação, ao arrumar a casa ou para fechar o dia.','[{"k": "Marca", "v": "Shankar, Índia"}, {"k": "Linha", "v": "Nag Champa Series"}, {"k": "Tipo", "v": "Massala, em varetas"}, {"k": "Aroma", "v": "Nag Champa"}]'::jsonb,'Acenda a ponta, deixe a chama queimar por alguns segundos e apague com um sopro leve. Use sempre um incensário.','Mantenha longe de cortinas, crianças e animais. Não deixe aceso sem ninguém por perto.','https://images.tcdn.com.br/img/img_prod/1222340/incenso_shankar_massala_nag_champa_nag_champa_series_2169_1_c4fada9a4e9b4d1f2cb17a17a43fe7e9.png','[]'::jsonb,'[]'::jsonb,'','Incenso Shankar Massala Nag Champa | Loja ARA','Incenso indiano Shankar massala Nag Champa, artesanal, Nag Champa Series: aroma duradouro e menos fumaça. Loja ARA, envio para todo o Brasil.'),
('incenso-shankar-sai-baba','Incenso Shankar Massala Sai Baba','incenso',10,3.67,1,true,true,true,21,'Novo','Floral e adocicado, para oração e meditação.','A Shankar produz incensos artesanais na Índia desde 1964. O massala é feito de uma massa de resinas, ervas, especiarias e óleos essenciais enrolada na vareta: por isso o aroma é mais rico e duradouro, com menos fumaça que os incensos comuns.

Acenda no início de uma meditação, ao arrumar a casa ou para fechar o dia.','[{"k": "Marca", "v": "Shankar, Índia"}, {"k": "Linha", "v": "Nag Champa Series"}, {"k": "Tipo", "v": "Massala, em varetas"}, {"k": "Aroma", "v": "Sai Baba"}]'::jsonb,'Acenda a ponta, deixe a chama queimar por alguns segundos e apague com um sopro leve. Use sempre um incensário.','Mantenha longe de cortinas, crianças e animais. Não deixe aceso sem ninguém por perto.','https://images.tcdn.com.br/img/img_prod/1222340/incenso_shankar_massala_sai_baba_nag_champa_series_2157_1_df941c345f4ff3959b90fa3a8686d1ea.png','[]'::jsonb,'[]'::jsonb,'','Incenso Shankar Massala Sai Baba | Loja ARA','Incenso indiano Shankar massala Sai Baba, artesanal, Nag Champa Series: aroma duradouro e menos fumaça. Loja ARA, envio para todo o Brasil.'),
('incenso-shankar-rosa-vermelha','Incenso Shankar Massala Rosa Vermelha','incenso',10,3.67,1,true,true,true,22,'Novo','Rosa intensa, para o amor e o acolhimento.','A Shankar produz incensos artesanais na Índia desde 1964. O massala é feito de uma massa de resinas, ervas, especiarias e óleos essenciais enrolada na vareta: por isso o aroma é mais rico e duradouro, com menos fumaça que os incensos comuns.

Acenda no início de uma meditação, ao arrumar a casa ou para fechar o dia.','[{"k": "Marca", "v": "Shankar, Índia"}, {"k": "Linha", "v": "Nag Champa Series"}, {"k": "Tipo", "v": "Massala, em varetas"}, {"k": "Aroma", "v": "Rosa Vermelha"}]'::jsonb,'Acenda a ponta, deixe a chama queimar por alguns segundos e apague com um sopro leve. Use sempre um incensário.','Mantenha longe de cortinas, crianças e animais. Não deixe aceso sem ninguém por perto.','https://images.tcdn.com.br/img/img_prod/1222340/incenso_shankar_massala_rosa_vermelha_nag_champa_series_2161_1_56584d5ae3805bf53e48b8a10b3b8072.png','[]'::jsonb,'[]'::jsonb,'','Incenso Shankar Massala Rosa Vermelha | Loja ARA','Incenso indiano Shankar massala Rosa Vermelha, artesanal, Nag Champa Series: aroma duradouro e menos fumaça. Loja ARA, envio para todo o Brasil.'),
('incenso-shankar-rosa-branca','Incenso Shankar Massala Rosa Branca','incenso',10,3.67,1,true,true,true,23,'Novo','Rosa suave, para a paz e a harmonia da casa.','A Shankar produz incensos artesanais na Índia desde 1964. O massala é feito de uma massa de resinas, ervas, especiarias e óleos essenciais enrolada na vareta: por isso o aroma é mais rico e duradouro, com menos fumaça que os incensos comuns.

Acenda no início de uma meditação, ao arrumar a casa ou para fechar o dia.','[{"k": "Marca", "v": "Shankar, Índia"}, {"k": "Linha", "v": "Nag Champa Series"}, {"k": "Tipo", "v": "Massala, em varetas"}, {"k": "Aroma", "v": "Rosa Branca"}]'::jsonb,'Acenda a ponta, deixe a chama queimar por alguns segundos e apague com um sopro leve. Use sempre um incensário.','Mantenha longe de cortinas, crianças e animais. Não deixe aceso sem ninguém por perto.','https://images.tcdn.com.br/img/img_prod/1222340/incenso_shankar_massala_rosa_branca_nag_champa_series_2145_1_5a81f6ab801a46e8ecc5f55f6805c0ce.png','[]'::jsonb,'[]'::jsonb,'','Incenso Shankar Massala Rosa Branca | Loja ARA','Incenso indiano Shankar massala Rosa Branca, artesanal, Nag Champa Series: aroma duradouro e menos fumaça. Loja ARA, envio para todo o Brasil.'),
('incenso-shankar-orquidea-francesa','Incenso Shankar Massala Orquídea Francesa','incenso',10,3.67,1,true,true,true,24,'Novo','Floral delicado e elegante.','A Shankar produz incensos artesanais na Índia desde 1964. O massala é feito de uma massa de resinas, ervas, especiarias e óleos essenciais enrolada na vareta: por isso o aroma é mais rico e duradouro, com menos fumaça que os incensos comuns.

Acenda no início de uma meditação, ao arrumar a casa ou para fechar o dia.','[{"k": "Marca", "v": "Shankar, Índia"}, {"k": "Linha", "v": "Nag Champa Series"}, {"k": "Tipo", "v": "Massala, em varetas"}, {"k": "Aroma", "v": "Orquídea Francesa"}]'::jsonb,'Acenda a ponta, deixe a chama queimar por alguns segundos e apague com um sopro leve. Use sempre um incensário.','Mantenha longe de cortinas, crianças e animais. Não deixe aceso sem ninguém por perto.','https://images.tcdn.com.br/img/img_prod/1222340/incenso_shankar_massala_orquidea_francesa_nag_champa_series_2143_1_ce9207c1b3f722a798579828cb0a0663.png','[]'::jsonb,'[]'::jsonb,'','Incenso Shankar Massala Orquídea Francesa | Loja ARA','Incenso indiano Shankar massala Orquídea Francesa, artesanal, Nag Champa Series: aroma duradouro e menos fumaça. Loja ARA, envio para todo o Brasil.'),
('incenso-shankar-lavanda','Incenso Shankar Massala Lavanda','incenso',10,3.67,1,true,true,true,25,'Novo','Calma e relaxamento para fechar o dia.','A Shankar produz incensos artesanais na Índia desde 1964. O massala é feito de uma massa de resinas, ervas, especiarias e óleos essenciais enrolada na vareta: por isso o aroma é mais rico e duradouro, com menos fumaça que os incensos comuns.

Acenda no início de uma meditação, ao arrumar a casa ou para fechar o dia.','[{"k": "Marca", "v": "Shankar, Índia"}, {"k": "Linha", "v": "Nag Champa Series"}, {"k": "Tipo", "v": "Massala, em varetas"}, {"k": "Aroma", "v": "Lavanda"}]'::jsonb,'Acenda a ponta, deixe a chama queimar por alguns segundos e apague com um sopro leve. Use sempre um incensário.','Mantenha longe de cortinas, crianças e animais. Não deixe aceso sem ninguém por perto.','https://images.tcdn.com.br/img/img_prod/1222340/incenso_shankar_massala_lavanda_nag_champa_series_2173_1_839c5306471ae18a29d97afdd1512142.png','[]'::jsonb,'[]'::jsonb,'','Incenso Shankar Massala Lavanda | Loja ARA','Incenso indiano Shankar massala Lavanda, artesanal, Nag Champa Series: aroma duradouro e menos fumaça. Loja ARA, envio para todo o Brasil.'),
('incenso-shankar-shiva','Incenso Shankar Massala Shiva','incenso',10,3.67,1,true,true,true,26,'Novo','Amadeirado e intenso, para meditação e transformação.','A Shankar produz incensos artesanais na Índia desde 1964. O massala é feito de uma massa de resinas, ervas, especiarias e óleos essenciais enrolada na vareta: por isso o aroma é mais rico e duradouro, com menos fumaça que os incensos comuns.

Acenda no início de uma meditação, ao arrumar a casa ou para fechar o dia.','[{"k": "Marca", "v": "Shankar, Índia"}, {"k": "Linha", "v": "Nag Champa Series"}, {"k": "Tipo", "v": "Massala, em varetas"}, {"k": "Aroma", "v": "Shiva"}]'::jsonb,'Acenda a ponta, deixe a chama queimar por alguns segundos e apague com um sopro leve. Use sempre um incensário.','Mantenha longe de cortinas, crianças e animais. Não deixe aceso sem ninguém por perto.','https://images.tcdn.com.br/img/img_prod/1222340/incenso_shankar_massala_shiva_nag_champa_series_2133_1_d20f253c8bf3437f7161696140fb1091.png','[]'::jsonb,'[]'::jsonb,'','Incenso Shankar Massala Shiva | Loja ARA','Incenso indiano Shankar massala Shiva, artesanal, Nag Champa Series: aroma duradouro e menos fumaça. Loja ARA, envio para todo o Brasil.'),
('incenso-shankar-canfora','Incenso Shankar Massala Cânfora','incenso',10,3.67,1,true,true,true,27,'Novo','Limpeza do ambiente e clareza mental.','A Shankar produz incensos artesanais na Índia desde 1964. O massala é feito de uma massa de resinas, ervas, especiarias e óleos essenciais enrolada na vareta: por isso o aroma é mais rico e duradouro, com menos fumaça que os incensos comuns.

Acenda no início de uma meditação, ao arrumar a casa ou para fechar o dia.','[{"k": "Marca", "v": "Shankar, Índia"}, {"k": "Linha", "v": "Nag Champa Series"}, {"k": "Tipo", "v": "Massala, em varetas"}, {"k": "Aroma", "v": "Cânfora"}]'::jsonb,'Acenda a ponta, deixe a chama queimar por alguns segundos e apague com um sopro leve. Use sempre um incensário.','Mantenha longe de cortinas, crianças e animais. Não deixe aceso sem ninguém por perto.','https://images.tcdn.com.br/img/img_prod/1222340/incenso_shankar_massala_canfora_nag_champa_series_2165_1_38498f77deceb40a25e25eebf37a5a13.png','[]'::jsonb,'[]'::jsonb,'','Incenso Shankar Massala Cânfora | Loja ARA','Incenso indiano Shankar massala Cânfora, artesanal, Nag Champa Series: aroma duradouro e menos fumaça. Loja ARA, envio para todo o Brasil.'),
('incenso-shankar-citronela','Incenso Shankar Massala Citronela','incenso',10,3.67,2,true,true,true,28,'Novo','Fresco e cítrico, ajuda a afastar os insetos.','A Shankar produz incensos artesanais na Índia desde 1964. O massala é feito de uma massa de resinas, ervas, especiarias e óleos essenciais enrolada na vareta: por isso o aroma é mais rico e duradouro, com menos fumaça que os incensos comuns.

Acenda no início de uma meditação, ao arrumar a casa ou para fechar o dia.','[{"k": "Marca", "v": "Shankar, Índia"}, {"k": "Linha", "v": "Nag Champa Series"}, {"k": "Tipo", "v": "Massala, em varetas"}, {"k": "Aroma", "v": "Citronela"}]'::jsonb,'Acenda a ponta, deixe a chama queimar por alguns segundos e apague com um sopro leve. Use sempre um incensário.','Mantenha longe de cortinas, crianças e animais. Não deixe aceso sem ninguém por perto.','https://wxkwkfkidigeuupaajre.supabase.co/storage/v1/object/public/ara/produtos/1790961787018-incenso-shankar-massala.jpg','[]'::jsonb,'[]'::jsonb,'','Incenso Shankar Massala Citronela | Loja ARA','Incenso indiano Shankar massala Citronela, artesanal, Nag Champa Series: aroma duradouro e menos fumaça. Loja ARA, envio para todo o Brasil.'),
('incenso-shankar-mirra','Incenso Shankar Massala Mirra','incenso',10,3.67,2,true,true,true,29,'Novo','Resina sagrada, para proteção e purificação.','A Shankar produz incensos artesanais na Índia desde 1964. O massala é feito de uma massa de resinas, ervas, especiarias e óleos essenciais enrolada na vareta: por isso o aroma é mais rico e duradouro, com menos fumaça que os incensos comuns.

Acenda no início de uma meditação, ao arrumar a casa ou para fechar o dia.','[{"k": "Marca", "v": "Shankar, Índia"}, {"k": "Linha", "v": "Nag Champa Series"}, {"k": "Tipo", "v": "Massala, em varetas"}, {"k": "Aroma", "v": "Mirra"}]'::jsonb,'Acenda a ponta, deixe a chama queimar por alguns segundos e apague com um sopro leve. Use sempre um incensário.','Mantenha longe de cortinas, crianças e animais. Não deixe aceso sem ninguém por perto.','https://images.tcdn.com.br/img/img_prod/1222340/incenso_shankar_massala_mirra_nag_champa_series_2127_1_bea4b17c12af9f3ac8add4b7a3b5be6a.png','[]'::jsonb,'[]'::jsonb,'','Incenso Shankar Massala Mirra | Loja ARA','Incenso indiano Shankar massala Mirra, artesanal, Nag Champa Series: aroma duradouro e menos fumaça. Loja ARA, envio para todo o Brasil.'),
('isqueiro-bic-maxi','Isqueiro BIC Maxi','acessorio',15,0,null,true,true,true,40,'Novo','Para acender o incenso, a vela e o palo santo.','O isqueiro BIC Maxi é o clássico de chama firme, com até 3.000 acendimentos.

Deixe um perto do seu altar ou do incensário: assim o ritual começa na hora.','[{"k": "Marca", "v": "BIC"}, {"k": "Modelo", "v": "Maxi (tamanho grande)"}, {"k": "Cor", "v": "Sortida, conforme o estoque"}]'::jsonb,'Gire a roda e pressione o botão. Para acender o incenso, incline a vareta sobre a chama por alguns segundos.','Mantenha longe do alcance de crianças, do calor e do sol direto.','','[]'::jsonb,'[]'::jsonb,'','Isqueiro BIC Maxi | Loja ARA','Isqueiro BIC Maxi, chama firme, para acender incensos, velas e palo santo. Loja ARA, envio para todo o Brasil.')
on conflict (slug) do nothing;

-- o produto antigo, com os aromas juntos, sai da loja (o endereço antigo leva ao Nag Champa)
update public.ara_produtos set ativo = false, disponivel = false, estoque = 0, atualizado_em = now() where slug = 'incenso-shankar-massala';
