-- Categoria do produto: cristais aparecem primeiro na loja; o resto é acessório e complemento.
alter table public.ara_produtos add column if not exists categoria text not null default 'acessorio';
alter table public.ara_produtos drop constraint if exists ara_produtos_categoria_chk;
alter table public.ara_produtos add constraint ara_produtos_categoria_chk check (categoria in ('cristal', 'acessorio'));
-- o site lê as colunas uma a uma (custo e custos ficam de fora)
grant select (categoria) on public.ara_produtos to anon, authenticated;

-- Primeiros cristais da loja: entram esgotados e inativos; a publicação do site os ativa.
insert into public.ara_produtos (slug, nome, categoria, tag, frase, texto, preco, detalhes, uso, cuidados, disponivel, estoque, sem_adicional, ativo, ordem, seo_titulo, seo_descricao)
values
('drusa-de-ametista', 'Drusa de Ametista', 'cristal', 'Mais procurado',
 'Um pedaço de geodo brasileiro, com pontas violeta que guardam a luz do ambiente.',
 E'A drusa de ametista é um aglomerado de pequenas pontas de cristal que nascem juntas, dentro dos geodos do sul do Brasil. É uma das pedras mais queridas de quem começa uma coleção, e uma das mais bonitas para um cantinho de calma.\n\nNa tradição dos cristais, a ametista é associada à calma, ao sono tranquilo e à intuição. Muita gente a deixa no quarto, na mesa de cabeceira ou no espaço de meditação.\n\nCada drusa é única: escolhemos as peças uma a uma, pela cor e pelo brilho das pontas.',
 189,
 '[{"k":"Pedra","v":"Ametista natural (quartzo violeta)"},{"k":"Formato","v":"Drusa bruta"},{"k":"Origem","v":"Brasil"},{"k":"Observação","v":"Cada peça é natural: forma, cor e tamanho variam. Peça fotos da sua pelo WhatsApp."}]',
 'Deixe em um lugar onde bata luz natural: no quarto, no altar ou na mesa de trabalho. Para guardar junto com outros cristais, o ARA Santuário mantém cada peça separada e à vista.',
 'Evite sol direto por muitas horas, que pode desbotar a cor. Limpe com pincel macio ou pano seco; se precisar, água corrente rápida e seque bem.',
 false, 0, true, false, 0,
 'Drusa de Ametista natural bruta | Loja ARA',
 'Drusa de ametista natural do Brasil, escolhida à mão pela cor e pelo brilho. Cristal bruto para o quarto, o altar ou a meditação. Compre na Loja ARA.'),
('quartzo-rosa-bruto', 'Quartzo Rosa Bruto', 'cristal', 'Mais procurado',
 'A pedra rosada do amor e do amor-próprio, em estado bruto.',
 E'O quartzo rosa é um dos cristais mais conhecidos do mundo, e o Brasil está entre os seus grandes produtores. Em estado bruto, mostra a cor leitosa e suave que faz dele uma peça delicada para qualquer ambiente.\n\nNa tradição dos cristais, o quartzo rosa é a pedra do amor, do amor-próprio e da harmonia nas relações. É muito usado no quarto e em presentes para quem a gente quer bem.\n\nCada peça é única e escolhida à mão.',
 89,
 '[{"k":"Pedra","v":"Quartzo rosa natural"},{"k":"Formato","v":"Bruto"},{"k":"Origem","v":"Brasil"},{"k":"Observação","v":"Cada peça é natural: forma, cor e tamanho variam. Peça fotos da sua pelo WhatsApp."}]',
 'No quarto, na sala ou junto de fotos de quem você ama. Também fica bonito sobre uma bandeja, ao lado de outros cristais.',
 'Evite sol direto por longos períodos, que pode clarear a cor. Limpe com pano seco ou água corrente e seque bem.',
 false, 0, true, false, 1,
 'Quartzo Rosa bruto natural | Loja ARA',
 'Quartzo rosa bruto natural do Brasil, a pedra do amor e do amor-próprio na tradição dos cristais. Peça escolhida à mão. Compre na Loja ARA.'),
('turmalina-negra-bruta', 'Turmalina Negra Bruta', 'cristal', 'Proteção',
 'A pedra preta mais procurada para proteger a casa e a energia.',
 E'A turmalina negra, também chamada de schorlita, cresce em bastões estriados de um preto profundo. O Brasil tem algumas das turmalinas mais bonitas do mundo.\n\nNa tradição dos cristais, ela é a pedra da proteção: muita gente coloca uma na entrada de casa, perto do computador ou carrega consigo para se sentir mais firme.\n\nCada bastão é único e escolhido à mão.',
 69,
 '[{"k":"Pedra","v":"Turmalina negra natural (schorlita)"},{"k":"Formato","v":"Bruta, em bastão"},{"k":"Origem","v":"Brasil"},{"k":"Observação","v":"Cada peça é natural: forma, cor e tamanho variam. Peça fotos da sua pelo WhatsApp."}]',
 'Na entrada de casa, na mesa de trabalho ou na bolsa. Para levar com você, o ARA Porta-Cristais protege a pedra no dia a dia.',
 'É uma pedra que pode lascar: evite quedas. Limpe com pincel macio ou pano seco e não deixe de molho.',
 false, 0, true, false, 2,
 'Turmalina Negra bruta natural | Loja ARA',
 'Turmalina negra bruta natural do Brasil, a pedra da proteção na tradição dos cristais. Bastão escolhido à mão. Compre na Loja ARA.'),
('drusa-de-citrino', 'Drusa de Citrino', 'cristal', 'Prosperidade',
 'O dourado do sol, em pontas de cristal.',
 E'Pontas de cristal em tons de mel e âmbar, reunidas em uma drusa. O citrino é um dos cristais mais procurados por quem monta um cantinho de prosperidade.\n\nNa tradição dos cristais, o citrino é associado à prosperidade, à alegria e à energia para começar projetos. É comum deixá-lo no escritório, no caixa da loja ou perto da entrada.\n\nCada drusa é única e escolhida à mão, pela cor e pelo brilho.',
 149,
 '[{"k":"Pedra","v":"Quartzo citrino"},{"k":"Formato","v":"Drusa bruta"},{"k":"Cor","v":"Tom dourado, em geral obtido pelo aquecimento da ametista"},{"k":"Observação","v":"Cada peça é natural: forma, cor e tamanho variam. Peça fotos da sua pelo WhatsApp."}]',
 'No escritório, na mesa de trabalho ou na entrada. Combina com a pirita em um cantinho de prosperidade.',
 'Evite sol direto por longos períodos. Limpe com pincel macio ou pano seco.',
 false, 0, true, false, 3,
 'Drusa de Citrino | Loja ARA',
 'Drusa de citrino em tons de mel e âmbar, o cristal da prosperidade na tradição dos cristais. Peça escolhida à mão. Compre na Loja ARA.'),
('pirita-bruta', 'Pirita Bruta', 'cristal', 'Prosperidade',
 'O ouro dos tolos: brilha como metal e já nasce em cubos.',
 E'A pirita forma cubos e cristais de brilho metálico, tão perfeitos que parecem lapidados, mas nascem assim na natureza. Por isso ganhou o apelido de ouro dos tolos.\n\nNa tradição dos cristais, a pirita é associada à prosperidade, à abundância e à proteção do que é seu. Aparece na mesa de trabalho, no caixa e até na carteira.\n\nCada peça é única e escolhida à mão, pelo brilho.',
 79,
 '[{"k":"Pedra","v":"Pirita natural"},{"k":"Formato","v":"Bruta"},{"k":"Observação","v":"Cada peça é natural: forma, cor e tamanho variam. Peça fotos da sua pelo WhatsApp."}]',
 'Na mesa de trabalho, no caixa, na carteira ou ao lado do citrino.',
 'Mantenha longe da água e da umidade, que tiram o brilho. Limpe só com pano seco.',
 false, 0, true, false, 4,
 'Pirita bruta natural | Loja ARA',
 'Pirita bruta natural, de brilho metálico, a pedra da prosperidade na tradição dos cristais. Peça escolhida à mão. Compre na Loja ARA.'),
('ponta-de-cristal', 'Ponta de Cristal', 'cristal', 'Essencial',
 'O quartzo transparente, a pedra mais clássica de todas.',
 E'A ponta de cristal é o quartzo transparente na sua forma natural: seis faces que terminam em uma ponta. O Brasil é um dos maiores produtores de quartzo do mundo.\n\nNa tradição dos cristais, o quartzo transparente é a pedra da clareza, o cristal que acompanha qualquer outra pedra e amplifica a sua intenção. Por isso é a primeira peça de muitas coleções.\n\nCada ponta é única e escolhida à mão, pela transparência.',
 79,
 '[{"k":"Pedra","v":"Quartzo transparente natural (cristal)"},{"k":"Formato","v":"Ponta bruta"},{"k":"Origem","v":"Brasil"},{"k":"Observação","v":"Cada peça é natural: forma, cor e tamanho variam. Peça fotos da sua pelo WhatsApp."}]',
 'Sobre a mesa, no altar ou junto de outros cristais. No ARA Santuário, ela fica no centro da coleção.',
 'Pode ir à água corrente. Seque bem e evite quedas, que lascam a ponta.',
 false, 0, true, false, 5,
 'Ponta de Cristal: quartzo transparente bruto | Loja ARA',
 'Ponta de cristal de quartzo transparente natural do Brasil, a pedra da clareza na tradição dos cristais. Escolhida à mão. Compre na Loja ARA.')
on conflict (slug) do nothing;
