-- Chaveiros, gargantilha e brinco encontrados no estoque: uma unidade de cada, com a foto da própria peça.
-- Entram ocultos; a publicação do site (com as fotos) os ativa.
insert into public.ara_produtos (slug, nome, categoria, tag, frase, texto, preco, detalhes, uso, cuidados, foto_url, disponivel, estoque, sem_adicional, ativo, ordem, seo_titulo, seo_descricao)
values
('chaveiro-om-chakras', 'Chaveiro OM Chakras', 'acessorio', 'Novo',
 'O primeiro som do universo, com as cores dos sete chakras.',
 E'Na tradição hindu, o OM é o som primordial, a vibração que deu origem ao universo. É entoado no início e no fim das meditações para acalmar a mente e purificar o ambiente.\n\nNeste chaveiro dourado, o símbolo do OM é rodeado por sete pedrinhas coloridas, uma para cada chakra. Um lembrete de equilíbrio para levar junto das chaves todos os dias.',
 50,
 '[{"k": "Tamanho", "v": "34 mm"}, {"k": "Acabamento", "v": "Dourado, com pedrinhas nas cores dos chakras"}, {"k": "Símbolo", "v": "OM, o som primordial"}]',
 'Leve com as chaves de casa ou do carro, ou pendure na bolsa.',
 'Evite contato com água, perfume e produtos de limpeza. Guarde separado das outras peças, num saquinho, para não riscar.',
 '/img/loja/chaveiro-om-chakras.83559afd.jpg',
 true, 1, true, false, 20,
 'Chaveiro OM Chakras dourado 34 mm | Loja ARA',
 'Chaveiro dourado com o símbolo do OM e sete pedrinhas nas cores dos chakras, 34 mm. O som primordial para levar com você. Loja ARA.'),
('chaveiro-hamsa-olho-grego', 'Chaveiro Hamsá com Olho Grego', 'acessorio', 'Novo',
 'Proteção, bênção, poder e força, junto das suas chaves.',
 E'A Hamsá, a mão aberta com cinco dedos, é um amuleto de proteção usado há milênios no Oriente Médio e no Norte da África. Representa bênção, poder e força, e afasta as energias negativas.\n\nNo centro, o olho grego reforça a proteção contra o mau-olhado. Um chaveiro prateado para levar a proteção para onde você for.',
 50,
 '[{"k": "Tamanho", "v": "30 mm"}, {"k": "Acabamento", "v": "Prateado, com olho grego azul"}, {"k": "Símbolo", "v": "Hamsá e olho grego, proteção"}]',
 'Leve com as chaves de casa ou do carro, ou pendure na bolsa. Na tradição, a Hamsá com os dedos para cima protege; com os dedos para baixo, atrai abundância.',
 'Evite contato com água, perfume e produtos de limpeza. Guarde separado das outras peças, num saquinho, para não riscar.',
 '/img/loja/chaveiro-hamsa-olho-grego.eeef3de5.jpg',
 true, 1, true, false, 21,
 'Chaveiro Hamsá com Olho Grego, amuleto de proteção | Loja ARA',
 'Chaveiro prateado da mão de Hamsá com olho grego, 30 mm: amuleto de proteção, bênção e força contra o mau-olhado. Loja ARA.'),
('gargantilha-mini-cristais', 'Gargantilha Mini Cristais', 'acessorio', 'Novo',
 'Um pequeno relicário de cristais para usar junto ao coração.',
 E'Uma gargantilha dourada e delicada, com um pingente redondo que guarda pequenos cristais à vista, como um relicário.\n\nLeve e fácil de combinar, acompanha um cartão de presente com espaço para escrever de quem e para quem. Um presente com significado.',
 80,
 '[{"k": "Pingente", "v": "18 mm, com mini cristais"}, {"k": "Acabamento", "v": "Dourado"}, {"k": "Presente", "v": "Acompanha cartão com De e Para"}]',
 'Use junto ao peito, perto do chakra do coração, para manter os cristais sempre por perto.',
 'Evite contato com água, perfume e produtos de limpeza. Guarde separado das outras peças, num saquinho, para não riscar.',
 '/img/loja/gargantilha-mini-cristais.bb816c8a.jpg',
 true, 1, true, false, 22,
 'Gargantilha Mini Cristais dourada, pingente 18 mm | Loja ARA',
 'Gargantilha dourada com pingente de 18 mm que guarda mini cristais, como um relicário. Acompanha cartão de presente. Loja ARA.'),
('brinco-filtro-dos-sonhos', 'Brinco Filtro dos Sonhos', 'acessorio', 'Novo',
 'Filtra as energias, purifica e traz bem-estar.',
 E'O filtro dos sonhos vem da tradição dos povos nativos da América do Norte: a teia segura os sonhos ruins e deixa passar os bons, que descem pelas penas até quem dorme.\n\nNeste brinco dourado e vazado, a teia e as penas balançam leves a cada movimento. Um amuleto para filtrar as energias e trazer bem-estar.',
 65,
 '[{"k": "Tamanho", "v": "De 20 a 35 mm"}, {"k": "Acabamento", "v": "Dourado, vazado, com penas"}, {"k": "Símbolo", "v": "Filtro dos sonhos"}]',
 'Use no dia a dia ou em ocasiões especiais. Por ser leve, é confortável para usar o dia todo.',
 'Evite contato com água, perfume e produtos de limpeza. Guarde separado das outras peças, num saquinho, para não riscar.',
 '/img/loja/brinco-filtro-dos-sonhos.9327c9d7.jpg',
 true, 1, true, false, 23,
 'Brinco Filtro dos Sonhos dourado | Loja ARA',
 'Brinco dourado de filtro dos sonhos com penas, de 20 a 35 mm: amuleto que filtra as energias e traz bem-estar. Loja ARA.'),
('chaveiro-caveira', 'Chaveiro Caveira', 'acessorio', 'Novo',
 'Dourado, cravejado de strass, para quem tem atitude.',
 E'Um chaveiro com caveira e ossos cruzados, dourado e cravejado de strass, com olhos pretos que se destacam.\n\nVem com argola e mosquetão: dá para usar nas chaves ou pendurar na bolsa e na mochila.',
 70,
 '[{"k": "Acabamento", "v": "Dourado, com strass e olhos pretos"}, {"k": "Fecho", "v": "Argola e mosquetão"}]',
 'Use com as chaves ou prenda o mosquetão na alça da bolsa ou da mochila.',
 'Evite contato com água, perfume e produtos de limpeza. Guarde separado das outras peças, num saquinho, para não riscar.',
 '/img/loja/chaveiro-caveira.0cfa3e1a.jpg',
 true, 1, true, false, 24,
 'Chaveiro Caveira dourado com strass | Loja ARA',
 'Chaveiro de caveira dourada com strass e olhos pretos, com argola e mosquetão para chaves, bolsa ou mochila. Loja ARA.'),
('chaveiro-pimenta', 'Chaveiro Pimenta', 'acessorio', 'Novo',
 'A pimenta que espanta o olho gordo.',
 E'Na tradição popular brasileira, a pimenta vermelha é um amuleto contra a inveja e o mau-olhado: é ela que "espanta o olho gordo" da casa e do trabalho.\n\nEste chaveiro traz uma pimenta esmaltada em vermelho, com folhas verdes e pontos de strass, presa a uma argola e um mosquetão dourados.',
 70,
 '[{"k": "Acabamento", "v": "Esmaltado vermelho, com strass e detalhes dourados"}, {"k": "Fecho", "v": "Argola e mosquetão"}, {"k": "Símbolo", "v": "Pimenta, proteção contra o mau-olhado"}]',
 'Use com as chaves ou prenda o mosquetão na alça da bolsa, para levar a proteção junto com você.',
 'Evite contato com água, perfume e produtos de limpeza. Guarde separado das outras peças, num saquinho, para não riscar.',
 '/img/loja/chaveiro-pimenta.0ef5f796.jpg',
 true, 1, true, false, 25,
 'Chaveiro Pimenta contra mau-olhado | Loja ARA',
 'Chaveiro de pimenta vermelha esmaltada com strass, amuleto popular contra a inveja e o mau-olhado. Com argola e mosquetão. Loja ARA.'),
('chaveiro-elefante', 'Chaveiro Elefante', 'acessorio', 'Novo',
 'Sorte, sabedoria e força, num elefante abraçado a uma pedra azul.',
 E'Em muitas culturas do Oriente, o elefante é símbolo de sorte, sabedoria e força. Na tradição, com a tromba para cima ele atrai a boa sorte.\n\nNeste chaveiro, um elefante em dourado envelhecido, todo trabalhado, abraça uma grande pedra facetada azul, com detalhes em strass.',
 70,
 '[{"k": "Acabamento", "v": "Dourado envelhecido, com pedra facetada azul e strass"}, {"k": "Fecho", "v": "Argola e mosquetão"}, {"k": "Símbolo", "v": "Elefante, sorte e sabedoria"}]',
 'Use com as chaves ou prenda o mosquetão na alça da bolsa.',
 'Evite contato com água, perfume e produtos de limpeza. Guarde separado das outras peças, num saquinho, para não riscar.',
 '/img/loja/chaveiro-elefante.ffb4e4d5.jpg',
 true, 1, true, false, 26,
 'Chaveiro Elefante da sorte com pedra azul | Loja ARA',
 'Chaveiro de elefante em dourado envelhecido com pedra facetada azul e strass: símbolo de sorte, sabedoria e força. Loja ARA.')
on conflict (slug) do nothing;
